version: '3.3'
services:

  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Boonkuae@2018"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S db1.internal.prod.example.com -U SA -P 'Boonkuae@2018' -Q 'select 1'
    networks:
      mynetwork:
        aliases:
          - db1.internal.prod.example.com
networks:
  mynetwork:
    driver: bridge